version: "3.1"

services:
  app:
    build:
      context: ./
      dockerfile: ./app.Dockerfile
    container_name: app
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_ENV=development
      - APP_HOST=0.0.0.0
      - APP_PORT=4000
      - DB_HOST=localhost
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - DB_USER=pg
      - DB_PASS=p0stgr3s
      - DB_POOL_MIN=5
      - DB_POOL_MAX=10
      - DB_IDLE_TIMEOUT=1000
      - DB_CONNECTION_TIMEOUT=1000
      - DB_MAX_USES=7500
      - PRIVATE_KEY_FILE=./keys/key.key
      - CERTIFICATE_FILE=./keys/certificate.crt
    networks:
      app-net: {}

  database:
    image: postgres:alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: p0stgr3s
    volumes:
      - ./data-db:/var/lib/postgresql/data
    networks:
      app-net: {}

networks:
  app-net:
    external: true
    name: "wildan-net"
