@host=http://0.0.0.0:4000

POST {{host}}/api/users/register
Content-Type: application/json

{
    "username":"wildananugrah",
    "password": "p@ssw0rd"
}

###
POST {{host}}/api/users/login
Content-Type: application/json

{
    "username":"wildananugrah",
    "password": "p@ssw0rd"
}